// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Metrictolookup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Metrictolookup));
        
        string IMigrationMetadata.Id
        {
            get { return "201411261509006_Metric to lookup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
