// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Metrics : IMigrationMetadata
    {
		private readonly ResourceManager Resources = new ResourceManager(typeof(Metrics));
        
        string IMigrationMetadata.Id
        {
			get { return "201412291550358_Metrics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
