// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ProductLineFeatureTypesThumbnailDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductLineFeatureTypesThumbnailDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201412081729062_ProductLine.FeatureTypes.Thumbnail.Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
