// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AdFlightCampaignjoining : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdFlightCampaignjoining));
        
        string IMigrationMetadata.Id
        {
            get { return "201412111945368_Ad-Flight-Campaign joining"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
