// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Creativepropertiesandcompositekey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creativepropertiesandcompositekey));
        
        string IMigrationMetadata.Id
        {
            get { return "201411051702502_Creative properties and composite key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
