// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CampaignAdsandAdPlatformNetworkApp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CampaignAdsandAdPlatformNetworkApp));
        
        string IMigrationMetadata.Id
        {
            get { return "201502041824512_Campaign.Ads and Ad.Platform.Network.App "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
