// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FeatureAdremoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeatureAdremoved));
        
        string IMigrationMetadata.Id
        {
            get { return "201504152022048_FeatureAd removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
