// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddChannelRemoveNetworkandPublisher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddChannelRemoveNetworkandPublisher));
        
        string IMigrationMetadata.Id
        {
            get { return "201506091413215_Add Channel. Remove Network and Publisher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
