// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ChannelNetwork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChannelNetwork));
        
        string IMigrationMetadata.Id
        {
            get { return "201506101758202_ChannelNetwork"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
