// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AdDestinationAd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdDestinationAd));
        
        string IMigrationMetadata.Id
        {
            get { return "201506041427190_AdDestinationAd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
