// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MinusFlight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MinusFlight));
        
        string IMigrationMetadata.Id
        {
            get { return "201503022117198_Minus Flight"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
