// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CmsModelSettingValidationadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CmsModelSettingValidationadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201505221504166_Cms Model-Setting-Validation added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
