// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdCMSPublishandCMSPublishStatusentities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdCMSPublishandCMSPublishStatusentities));
        
        string IMigrationMetadata.Id
        {
            get { return "201512151447036_created CMSPublish and CMSPublishStatus entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
