// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FeatureCategoryaddFeature_Idcolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeatureCategoryaddFeature_Idcolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201506091951229_FeatureCategory add Feature_Id column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
