// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addchannelonDeliveryGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addchannelonDeliveryGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201508111613527_add channel on DeliveryGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
