// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MergeModelpruning : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MergeModelpruning));
        
        string IMigrationMetadata.Id
        {
            get { return "201503241345444_Merge-Model pruning"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
