// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

	public sealed partial class Security : IMigrationMetadata
    {
		private readonly ResourceManager Resources = new ResourceManager(typeof(Security));
        
        string IMigrationMetadata.Id
        {
			get { return "201505081750017_Security"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
