// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adduniqueconstrainttonamecolumninCmslookuptables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduniqueconstrainttonamecolumninCmslookuptables));
        
        string IMigrationMetadata.Id
        {
            get { return "201601111832305_add unique constraint to name column in Cms lookup tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
