// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SetCommercialSpotAdTypeManifestNameinSql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetCommercialSpotAdTypeManifestNameinSql));
        
        string IMigrationMetadata.Id
        {
            get { return "201603151710448_Set Commercial Spot Ad Type Manifest Name in Sql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
