// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddManifestNameonResourceType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddManifestNameonResourceType));
        
        string IMigrationMetadata.Id
        {
            get { return "201603151557386_Add ManifestName on ResourceType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
