// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenamedCampaignAgencytoMediaAgency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamedCampaignAgencytoMediaAgency));
        
        string IMigrationMetadata.Id
        {
            get { return "201603161710325_Renamed Campaign Agency to MediaAgency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
