// <auto-generated />
namespace BrightLine.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ParentpropertyaddedtoAgency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ParentpropertyaddedtoAgency));
        
        string IMigrationMetadata.Id
        {
            get { return "201601251533060_Parent property added to Agency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
